### ISSUE TITLE
Support M1 and Android x64

### ISSUE THREAD

**Issue by pietpukkel** [axys1/buildware#5]
I've updated the buildscripts in my fork of buildware: see https://github.com/pietpukkel/buildware

Buildscript now builds (on my Mac) Mac x64 and arm64 binaries and the distribution scripts make them to fat libraries. I've also added x64 libraries for Android (have not been able to test the results yet). Delete all files in buildsrc after every build.

The only issue  that I have is in bulding libjitlua. Building seems to succeed for iOS/Mac but the resulting libs are most likely corrupted. Building for Android fails (for luajit). So these build steps need some TLC from someone with a bit more expertise than I have. I also see no test that actually uses this library. 

Assuming the windows powershell scripts only generate the libraries for windows, i have not touched these (or looked at them).

**Comment by pietpukkel** [comment]
Buildware is by the way not entirely complete as for Mac and iOS  glsl_optimizer (libglcpp-library, libglsl-optimizer.a and libmesa.a) is missing. I've build these for Mac using https://github.com/aras-p/glsl-optimizer (and just change target in xcode to standard platforms; intel and apple silicon).

**Comment by halx99** [comment]
The glsl-optimizer support cmake, maybe could be add to buildware also.

**Comment by pietpukkel** [comment]
Yes indeed! I've modified the build script to generate the library from https://github.com/cocos2d/glsl-optimizer. Tomorrow I'll clean the scripts, modify the distribution scripts and make sure these only can be build for iOS and OSX. 

From there the buildscripts should basically download and build everything (except perhaps luajit a I just cannot get those to work).

**Comment by pietpukkel** [comment]
Done. Last commit in my fork should now also generate glsl-optimizer libraries and add them to the release zip.

**Comment by halx99** [comment]
The glsl-optimizer only for mac/ios, so no needs to build windows for it.

**Comment by halx99** [comment]
Seems we can't cross compile osx arm64(M1) through github actions: 
![image](https://user-images.githubusercontent.com/6977319/184369893-effb3482-ede2-4a61-b280-0342bca17a94.png)

**Comment by halx99** [comment]
Apple M1 support is in github action roadmap, but not complete yet, refer to: https://github.com/github/roadmap/issues/528

**Comment by pietpukkel** [comment]
Hm.. what happens when you build the x86_64. Might be an error in the script (which runs for me but perhaps exactly opposite on a x86_64)?



Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by halx99** [comment]
You can refer to this action: https://github.com/axys1/buildware/actions/runs/2847209116

**Comment by halx99** [comment]
Let us wait the latest [action](https://github.com/axys1/buildware/actions/runs/2847236377) finished and dist again

**Comment by halx99** [comment]
Yes, maybe script error for openssl:
```sh
CONFIG_ALL_OPTIONS=darwin64-x86_64-cc no-tests no-comp no-async no-shared --prefix=/Users/runner/work/buildware/buildware/install_osx_arm64/openssl --openssldir=/Users/runner/work/buildware/buildware/install_osx_arm64/openssl
```

**Comment by pietpukkel** [comment]
I am checking. What architecture do you build on? Mac x64?

On 12 Aug 2022, at 16:20, 一线灵 ***@***.******@***.***>> wrote:



Yes, maybe script error for openssl:

CONFIG_ALL_OPTIONS=darwin64-x86_64-cc no-tests no-comp no-async no-shared --prefix=/Users/runner/work/buildware/buildware/install_osx_arm64/openssl --openssldir=/Users/runner/work/buildware/buildware/install_osx_arm64/openssl

**Comment by halx99** [comment]
Yes, the github action only provide macos x86_64 vm currently

**Comment by pietpukkel** [comment]
I learn new things everyday. I did not know these were build automatically in Git in VMs. That’s quite cool.

I think it was an error in buid1.sh. I’ve reversed the compilers and on my iMac Pro it now builds the M1 binaries. Sorry that I did not test that before.



On 12 Aug 2022, at 16:22, 一线灵 ***@***.******@***.***>> wrote:



Yes, the github action only provide macos x86_64 vm currently

**Comment by halx99** [comment]
The logic check seems incorrect:
https://github.com/axys1/buildware/blob/main/1k/build1.sh#L78

**Comment by halx99** [comment]
No worries, I will fix it

**Comment by pietpukkel** [comment]
Just ran it again in my x64 Mac and my latest commit also fixes it. No need for an M1 runner 😉

**Comment by halx99** [comment]
Good job

**Comment by halx99** [comment]
The openssl osx arm64 seems still failed:

/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
#error architecture not supported
 ^

**Comment by pietpukkel** [comment]
Might be due to the MacOS version of the runner and the commandline tools. Catelina does not support arm64 (only Big Sur and up). The scripts run correctly on a MacOS 12.5 system (Monterey). If you want I can run them for you.

**Comment by pietpukkel** [comment]
MacOSX10.15.sdk is too "old".

**Comment by pietpukkel** [comment]
I ran the scripts on my iMac pro with MacOS 12.5 for you (Intel machine). Results are attached. Both the build output (so you can see I actually ran the scripts) and the resulting zip  files. 

./1k/build.sh osx arm64 > result.txt
./1k/build.sh osx x64 > result1.txt
./1k/distr.h > result2.txt

Resulting zip of course only contains the Mac fat binaries.

I fear that for an automatic build using the Github VM we have to wait until they offer a 11.x or 12.x machine :-
[result.txt](https://github.com/axys1/buildware/files/9324732/result.txt)
[result1.txt](https://github.com/axys1/buildware/files/9324733/result1.txt)
<img width="667" alt="Screenshot 2022-08-12 at 18 07 47" src="https://user-images.githubusercontent.com/474574/184397133-aeb7af5d-6c86-4e1b-9dca-7a912e41d374.png">
[result2.txt](https://github.com/axys1/buildware/files/9324734/result2.txt)
[buildware_dist.zip](https://github.com/axys1/buildware/files/9324735/buildware_dist.zip)
(

**Comment by halx99** [comment]
> 

OK, I upgrade it, and works on github action: https://github.com/axys1/buildware/actions/runs/2849072550

**Comment by pietpukkel** [comment]
Looks like it worked 👍
